#!/usr/bin/env python3
"""Inventory of personal data in tracked files, before anything is published.

Scans every file git tracks at HEAD. Text files are searched for local user paths and common secrets in all the ways
they are written: plain (drive, Users, <name>), JSON-escaped with doubled backslashes, forward slashes, macOS and
Linux home paths, personal e-mail addresses and access tokens. Files that are not UTF-8
text (images, drawings, archives) are listed separately as NOT SCANNED: screenshots and nested archives need a
human look. Usernames are masked in the report, so the report does not add a new copy of them.
Usage: python3 scripts/scan_exposure.py [--json out.json] [--markdown out.md]"""
from pathlib import Path
import json, re, subprocess, sys
ROOT = Path(__file__).resolve().parent.parent
BS = re.escape('\\')
PATTERNS = [
    ('windows-user-path', re.compile(r'[A-Za-z]:(?:%s){1,2}Users(?:%s){1,2}([A-Za-z0-9._ -]{1,40}?)(?=%s|$|["\s,;)])' % (BS, BS, BS))),
    ('windows-user-path', re.compile(r'[A-Za-z]:/Users/([A-Za-z0-9._-]{1,40})')),
    ('macos-user-path', re.compile(r'/Users/([A-Za-z0-9._-]{1,40})(?=/|$|["\s,;)])')),
    ('linux-home-path', re.compile(r'/home/([A-Za-z0-9._-]{1,40})(?=/|$|["\s,;)])')),
    ('personal-email', re.compile(r'[A-Za-z0-9._%+-]+@(?:gmail|yahoo|outlook|hotmail|icloud|live|proton)\.(?:com|me)')),
    ('access-token', re.compile(r'gh[pousr]_[A-Za-z0-9]{20,}|github_pat_[A-Za-z0-9_]{20,}|AKIA[0-9A-Z]{16}|-----BEGIN [A-Z ]*PRIVATE KEY-----')),
]
IGNORED_NAMES = {'Shared', 'Public', 'runner', 'runneradmin', 'claude'}   # system/CI accounts, not people
def mask(v): return (v[:1] + '…') if v else v
def scan_text(text):
    found = []
    for kind, rx in PATTERNS:
        for m in rx.finditer(text):
            who = m.group(1) if m.groups() else None
            if who in IGNORED_NAMES: continue
            found.append((kind, mask(who) if who else '(value withheld)'))
    return found
def inventory(root=ROOT):
    files = subprocess.run(['git', 'ls-files', '-z'], cwd=root, capture_output=True, check=True).stdout.decode('utf-8').split('\0')
    hits, unscanned = {}, []
    for f in filter(None, files):
        data = (Path(root) / f).read_bytes()
        try:
            if b'\0' in data: raise UnicodeDecodeError('utf-8', b'', 0, 1, 'binary')
            text = data.decode('utf-8')
        except UnicodeDecodeError: unscanned.append(f); continue
        for kind, who in scan_text(text): hits.setdefault(f, set()).add('%s (%s)' % (kind, who))
    def git(*a):
        r = subprocess.run(['git', *a], cwd=root, capture_output=True, text=True); return r.stdout.strip() if r.returncode == 0 else None
    return {'scope': 'files tracked by git; working-tree bytes; text scan; usernames masked', 'commit': git('rev-parse', 'HEAD'), 'uncommitted_entries': len([l for l in (git('status', '--porcelain') or '').splitlines() if l.strip()]), 'files_with_findings': {f: sorted(v) for f, v in sorted(hits.items())}, 'not_scanned_binary': sorted(unscanned)}
def markdown(inv):
    kinds = {}
    for f, v in inv['files_with_findings'].items():
        for k in v: kinds.setdefault(k, []).append(f)
    L = ['# Exposure inventory', '', 'Scanned commit `%s`, %s.' % ((inv.get('commit') or 'unknown')[:12], 'clean working tree' if inv.get('uncommitted_entries') == 0 else '%s uncommitted entries' % inv.get('uncommitted_entries')), '', 'Generated by `scripts/scan_exposure.py` from the files git tracks. It masks usernames, so this report adds no new copy of them. It is a text scan: the binary files listed at the end have **not** been examined and need a human look (screenshots can show paths; drawings and archives can carry metadata).', '', '| Finding | Files |', '|---|---|']
    L += ['| %s | %d |' % (k, len(v)) for k, v in sorted(kinds.items())]
    L += ['', '## Files with findings', ''] + ['- `%s`: %s' % (f, ', '.join(v)) for f, v in inv['files_with_findings'].items()]
    L += ['', '## Not scanned (binary)', ''] + ['- `%s`' % f for f in inv['not_scanned_binary']]
    return '\n'.join(L) + '\n'
if __name__ == '__main__':
    inv = inventory(); args = sys.argv[1:]
    if '--json' in args: Path(args[args.index('--json') + 1]).write_text(json.dumps(inv, indent=1), encoding='utf-8')
    if '--markdown' in args: Path(args[args.index('--markdown') + 1]).write_text(markdown(inv), encoding='utf-8')
    print('files with findings: %d | binary files not scanned: %d' % (len(inv['files_with_findings']), len(inv['not_scanned_binary'])))
